#!/usr/bin/env python3
"""Per-output sidecar config (.igntui.cfg.toml).

Lives next to the generated `.gitignore`. Captures the selection that produced
the file so a teammate (or future-you) re-running `igntui` in the same
directory restores the same starting state. Safe to commit to git.
"""

import logging
import time
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import tomli_w

from .. import __version__

logger = logging.getLogger(__name__)

SIDECAR_FILENAME = ".igntui.cfg.toml"
LEGACY_SIDECAR_FILENAME = "igntui.cfg.toml"  # v0.0.x; auto-detected for one release
SCHEMA_VERSION = 1


@dataclass
class ProjectConfig:
    templates: list[str] = field(default_factory=list)
    search_mode: str = "fuzzy"
    output_path: str = ".gitignore"
    preserve_user_edits: bool = True
    generated_at: str | None = None
    igntui_version: str | None = None
    schema_version: int = SCHEMA_VERSION

    @classmethod
    def load(cls, path: Path) -> Optional["ProjectConfig"]:
        try:
            with open(path, "rb") as f:
                data = tomllib.load(f)
        except FileNotFoundError:
            return None
        except (OSError, tomllib.TOMLDecodeError) as e:
            logger.warning("Failed to load %s: %s", path, e)
            return None

        schema = data.get("schema_version", 1)
        if schema > SCHEMA_VERSION:
            logger.warning(
                "%s schema_version=%d is newer than this igntui supports (%d); "
                "loading best-effort",
                path,
                schema,
                SCHEMA_VERSION,
            )

        selection = data.get("selection", {}) or {}
        output = data.get("output", {}) or {}

        templates = selection.get("templates", [])
        if not isinstance(templates, list):
            logger.warning("%s [selection].templates must be a list; ignoring", path)
            templates = []
        templates = [str(t) for t in templates]

        return cls(
            templates=templates,
            search_mode=str(selection.get("search_mode", "fuzzy")),
            output_path=str(output.get("path", ".gitignore")),
            preserve_user_edits=bool(output.get("preserve_user_edits", True)),
            generated_at=data.get("generated_at"),
            igntui_version=data.get("igntui_version"),
            schema_version=int(schema),
        )

    def dump(self, path: Path) -> None:
        self.generated_at = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        self.igntui_version = __version__

        payload = {
            "schema_version": self.schema_version,
            "generated_at": self.generated_at,
            "igntui_version": self.igntui_version,
            "selection": {
                "templates": list(self.templates),
                "search_mode": self.search_mode,
            },
            "output": {
                "path": self.output_path,
                "preserve_user_edits": self.preserve_user_edits,
            },
        }

        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "wb") as f:
            f.write(
                b"# .igntui.cfg.toml \xe2\x80\x94 generated by igntui; safe to commit.\n"
                b"# Re-running igntui in this directory restores this selection.\n\n"
            )
            tomli_w.dump(payload, f)
        logger.info("Wrote project sidecar to %s", path)


def find_sidecar(start: Path | None = None) -> Path | None:
    """Return the path to .igntui.cfg.toml in the given directory if present.

    For one release window (v0.1.0), also recognizes the legacy non-dotted
    filename ``igntui.cfg.toml`` and logs a one-shot notice prompting the
    user to rename. The legacy name is dropped in v0.2.0.
    """
    base = start or Path.cwd()
    candidate = base / SIDECAR_FILENAME
    if candidate.is_file():
        return candidate

    legacy = base / LEGACY_SIDECAR_FILENAME
    if legacy.is_file():
        logger.info(
            "Found legacy sidecar %s — rename to %s; legacy name will be dropped in v0.2.0",
            legacy,
            SIDECAR_FILENAME,
        )
        return legacy
    return None
