#!/usr/bin/env python3


import argparse
import sys
from pathlib import Path

from ..base import CLICommand


class GenerateCommand(CLICommand):
    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        parser.add_argument(
            "templates", nargs="+", help="Template names to generate (space-separated)"
        )
        parser.add_argument(
            "--output",
            "-o",
            type=Path,
            metavar="FILE",
            help="Output file path (default: print to stdout)",
        )
        parser.add_argument(
            "--append",
            "-a",
            action="store_true",
            help="Append to existing file instead of overwriting",
        )
        parser.add_argument(
            "--force",
            "-f",
            action="store_true",
            help="Force overwrite without confirmation",
        )

    def execute(self, args: argparse.Namespace) -> int:
        try:
            if args.verbose:
                print(f"Generating .gitignore for: {', '.join(args.templates)}")

            response = self.cli.api.get_templates(args.templates)

            if not response.success:
                print(f"Error: {response.error_message}")
                return 1

            content = response.data

            if not content.strip():
                print("Warning: Generated content is empty")
                return 1

            if args.dry_run:
                if args.output:
                    size = len(content.encode("utf-8"))
                    print(
                        f"# (dry-run — would write {size} bytes to {args.output})",
                        file=sys.stderr,
                    )
                else:
                    print("# (dry-run — no file written)", file=sys.stderr)
                print(content)
                return 0

            if not args.output:
                print(content)
                return 0

            output_file = args.output

            if output_file.exists() and not args.append and not args.force:
                response_text = input(
                    f"File '{output_file}' exists. Overwrite? (y/N): "
                )
                if response_text.lower() not in ("y", "yes"):
                    print("Operation cancelled")
                    return 1

            try:
                if args.append:
                    with open(output_file, "a", encoding="utf-8") as f:
                        if output_file.stat().st_size > 0:
                            f.write("\n\n# Generated by igntui\n")
                        f.write(content)
                    print(f"✓ Appended to {output_file}")
                else:
                    from ...core.managed_block import merge as merge_managed_block

                    existing = None
                    if output_file.exists():
                        existing = output_file.read_text(encoding="utf-8")
                    merged = merge_managed_block(existing, content)
                    output_file.write_text(merged, encoding="utf-8")
                    print(f"✓ Generated {output_file}")

                    if not args.no_sidecar:
                        self._write_sidecar(output_file, args.templates)
                return 0

            except OSError as e:
                print(f"Error writing file: {e}")
                return 1

        except Exception as e:
            self.cli.handle_api_error(e)
            return 1

    def _write_sidecar(self, output_file: Path, templates: list[str]) -> None:
        from ...core.project_config import SIDECAR_FILENAME, ProjectConfig

        try:
            sidecar_path = output_file.parent / SIDECAR_FILENAME
            ProjectConfig(
                templates=list(templates),
                output_path=output_file.name,
            ).dump(sidecar_path)
            print(f"✓ Wrote {sidecar_path}")
        except Exception as e:
            print(f"Warning: could not write sidecar ({e})")
