#!/usr/bin/env python3
# -*- coding: utf-8 -*-


import argparse
import os
from pathlib import Path

from ..base import CLICommand


class GenerateCommand(CLICommand):
    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        parser.add_argument(
            "templates", nargs="+", help="Template names to generate (space-separated)"
        )
        parser.add_argument(
            "--output",
            "-o",
            type=Path,
            metavar="FILE",
            help="Output file path (default: print to stdout)",
        )
        parser.add_argument(
            "--append",
            "-a",
            action="store_true",
            help="Append to existing file instead of overwriting",
        )
        parser.add_argument(
            "--force",
            "-f",
            action="store_true",
            help="Force overwrite without confirmation",
        )

    def execute(self, args: argparse.Namespace) -> int:
        try:
            if hasattr(args, "verbose") and args.verbose:
                print(f"Generating .gitignore for: {', '.join(args.templates)}")

            response = self.cli.api.get_templates(args.templates)

            if not response.success:
                print(f"Error: {response.error_message}")
                return 1

            content = response.data

            if not content.strip():
                print("Warning: Generated content is empty")
                return 1

            if not args.output:
                print(content)
                return 0

            output_file = args.output

            if output_file.exists() and not args.append and not args.force:
                response_text = input(
                    f"File '{output_file}' exists. Overwrite? (y/N): "
                )
                if response_text.lower() not in ("y", "yes"):
                    print("Operation cancelled")
                    return 1

            mode = "a" if args.append else "w"
            try:
                with open(output_file, mode, encoding="utf-8") as f:
                    if args.append and output_file.stat().st_size > 0:
                        f.write("\n\n# Generated by igntui\n")
                    f.write(content)

                action = "Appended to" if args.append else "Generated"
                print(f"✓ {action} {output_file}")
                return 0

            except IOError as e:
                print(f"Error writing file: {e}")
                return 1

        except Exception as e:
            self.cli.handle_api_error(e)
            return 1
